# ===----------------------------------------------------------------------===#
# tools/ - 命令行工具总入口
# ===----------------------------------------------------------------------===#

add_subdirectory(edge-opt)
add_subdirectory(edge-introspect)
add_subdirectory(edge-memplan)
add_subdirectory(edge-run)
add_subdirectory(edge-quantize)
