// callingconv_description.cpp - Calling Convention Description and CCValAssign
//
// Demonstrates how to describe calling conventions using TableGen concepts,
// the CCState/CCValAssign family of classes, and the overall ABI lowering flow.

#include <cassert>
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

// ============================================================
// 1. Calling Convention infrastructure (simulated)
// ============================================================

// A calling convention is identified by an ID.
struct CallingConv {
  enum ID {
    C,
    Fast,
    Cold,
    // ... many more
  };
};

// Flags carried by arguments (e.g., signext, zeroext, inreg, etc.)
struct ArgFlagsTy {
  bool isSExt()  const { return SExt; }
  bool isZExt()  const { return ZExt; }
  bool isInReg() const { return InReg; }
  bool SExt = false, ZExt = false, InReg = false;
  // ... many more flags
};

// Value type (simulated MVT)
struct MVT {
  unsigned Size;
  bool isInteger() const { return true; }
  unsigned getSizeInBits() const { return Size; }
  static MVT i8()  { return {8}; }
  static MVT i16() { return {16}; }
  static MVT i32() { return {32}; }
  static MVT f32() { return {32}; }
};

// ============================================================
// 2. CCValAssign - the "identity card" of a lowered value
// ============================================================

struct CCValAssign {
  enum LocInfo {
    Full,   // No transformation needed (ValVT == LocVT)
    SExt,   // Sign-extend from ValVT to LocVT
    ZExt,   // Zero-extend from ValVT to LocVT
    AExt,   // Any-extend (don't care about high bits)
    BCvt,   // Bit-convert
    Indirect, // Passed indirectly (by address)
  };

  // Where does this value live?
  bool isRegLoc() const { return IsRegister; }
  bool isMemLoc() const { return !IsRegister; }

  // Get the location
  unsigned getLocReg()      const { return Loc; }  // Physical register
  unsigned getLocMemOffset() const { return Loc; }   // Stack offset

  // Original type (as declared in LLVM IR)
  MVT getValVT() const { return ValVT; }

  // Actual type (as stored in the physical location)
  MVT getLocVT() const { return LocVT; }

  // How to convert between ValVT and LocVT
  LocInfo getLocInfo() const { return Info; }

  // Internal fields
  bool IsRegister;
  unsigned Loc;       // Register number or memory offset
  MVT ValVT;          // Original type
  MVT LocVT;          // Type in the location
  LocInfo Info;       // Extension/conversion kind
};

// ============================================================
// 3. CCAssignFn - generated by TableGen (gen-callingconv)
// ============================================================

// This is the signature of the function generated by TableGen:
//   bool CC_XXX(unsigned ValNo, MVT ValVT, MVT LocVT,
//               CCValAssign::LocInfo LocInfo, ArgFlagsTy Flags,
//               CCState &State);
using CCAssignFn = std::function<bool(unsigned, MVT, MVT,
                                       CCValAssign::LocInfo,
                                       ArgFlagsTy, /*CCState&*/ void*)>;

// Simulated TableGen-generated calling convention function.
// This mimics what "gen-callingconv" produces.
bool CC_H2BLB_Common(unsigned ValNo, MVT ValVT, MVT LocVT,
                      CCValAssign::LocInfo LocInfo,
                      ArgFlagsTy Flags, void *State) {
  // In real code, this is generated from your CallingConv TableGen record.
  // The body evaluates CCAction records in order:
  //
  //   CCIfType<[v2i16], CCBitConvertToType<i32>>,
  //   CCIfType<[i16,f16], CCAssignToReg<[R1, R2, R3]>>,
  //   CCIfType<[i32,f32], CCAssignToReg<[D1]>>,
  //   CCAssignToStack<2, 2>
  //
  // For simulation, return true to indicate the location was assigned.
  (void)ValNo; (void)ValVT; (void)LocVT;
  (void)LocInfo; (void)Flags; (void)State;
  return true;
}

// ============================================================
// 4. CCState - manages the state of ABI lowering
// ============================================================

class CCState {
  std::vector<CCValAssign> &Locs;
  CallingConv::ID CallConv;
  bool IsVarArg;

public:
  CCState(CallingConv::ID CC, bool VarArg, std::vector<CCValAssign> &Locations)
    : Locs(Locations), CallConv(CC), IsVarArg(VarArg) {}

  // Analyze formal arguments: determines where each incoming argument lives.
  // This is called from LowerFormalArguments on the callee side.
  bool AnalyzeFormalArguments(
      const std::vector<std::pair<MVT, ArgFlagsTy>> &Ins,
      CCAssignFn Fn) {
    Locs.clear();
    for (size_t i = 0; i < Ins.size(); ++i) {
      MVT VT = Ins[i].first;
      ArgFlagsTy Flags = Ins[i].second;
      // The TableGen function fills in the location.
      // We simulate: if VT.getSizeInBits() <= 16, use register; else use stack.
      CCValAssign VA;
      if (VT.getSizeInBits() <= 16) {
        VA.IsRegister = true;
        VA.Loc = static_cast<unsigned>(i + 1); // R1, R2, R3...
        VA.ValVT = VT;
        VA.LocVT = MVT::i16(); // Promote to register width
        VA.Info = (VT.getSizeInBits() < 16) ? CCValAssign::SExt : CCValAssign::Full;
      } else {
        VA.IsRegister = false;
        VA.Loc = static_cast<unsigned>(i * 4); // Stack offset
        VA.ValVT = VT;
        VA.LocVT = VT;
        VA.Info = CCValAssign::Full;
      }
      Locs.push_back(VA);
    }
    return true;
  }

  // Analyze return values: determines where each return value lives.
  bool AnalyzeReturn(const std::vector<std::pair<MVT, ArgFlagsTy>> &Outs,
                     CCAssignFn Fn) {
    // Similar to AnalyzeFormalArguments but for outgoing return values.
    Locs.clear();
    for (size_t i = 0; i < Outs.size(); ++i) {
      CCValAssign VA;
      VA.IsRegister = true;
      VA.Loc = static_cast<unsigned>(100 + i); // Return registers
      VA.ValVT = Outs[i].first;
      VA.LocVT = Outs[i].first;
      VA.Info = CCValAssign::Full;
      Locs.push_back(VA);
    }
    return true;
  }

  // Check if a return value fits in registers (for sret demotion decision).
  bool CheckReturn(const std::vector<std::pair<MVT, ArgFlagsTy>> &Outs,
                   CCAssignFn Fn) {
    // Returns true if the return value can be passed in registers directly.
    // If the structure is too large, returns false -> sret demotion.
    size_t totalSize = 0;
    for (auto &Out : Outs)
      totalSize += Out.first.getSizeInBits();
    return totalSize <= 64; // Assume max 64 bits in registers
  }

  const std::vector<CCValAssign> &getLocs() const { return Locs; }
};

// ============================================================
// 5. ABI lowering example: LowerFormalArguments (callee side)
// ============================================================

// Simulated "MachineFunction" and related helpers
struct MachineFunction {
  std::vector<unsigned> LiveIns; // Physical registers that are live-in
};

// In SDISel, LowerFormalArguments is implemented in XXXTargetLowering.
// It uses CCState to determine locations, then creates SDNodes.

void lowerFormalArgumentsExample() {
  // Input: the function being lowered
  //   define i16 @foo(i16 %a, i8 %b)

  // Step 1: Gather the input argument descriptions
  std::vector<std::pair<MVT, ArgFlagsTy>> Ins;
  Ins.push_back({MVT::i16(), ArgFlagsTy{}}); // %a: i16
  Ins.push_back({MVT::i8(),  ArgFlagsTy{}}); // %b: i8

  // Step 2: Create CCState and analyze
  std::vector<CCValAssign> ArgLocs;
  CCState CCInfo(CallingConv::C, false, ArgLocs);
  CCInfo.AnalyzeFormalArguments(Ins, CC_H2BLB_Common);

  // Step 3: For each CCValAssign, generate the right sequence
  for (size_t i = 0; i < ArgLocs.size(); ++i) {
    const CCValAssign &VA = ArgLocs[i];

    if (VA.isRegLoc()) {
      // Argument in a register.
      unsigned PhysReg = VA.getLocReg();
      MVT RegVT = VA.getLocVT();

      // In SDISel:
      //   Register VReg = RegInfo.createVirtualRegister(DstRC);
      //   RegInfo.addLiveIn(PhysReg, VReg);
      //   SDValue ArgVal = DAG.getCopyFromReg(Chain, DL, VReg, RegVT);
      //   InVals.push_back(ArgVal);

      // In GlobalISel:
      //   Register VReg = MRI.createGenericVirtualRegister(LLT::scalar(RegVT.getSizeInBits()));
      //   MIRBuilder.buildCopy(VReg, PhysReg); // simplified

      // Handle extension if ValVT != LocVT
      if (VA.getLocInfo() == CCValAssign::SExt) {
        // Create a sign-extend instruction from LocVT to ValVT
        // In SDISel: DAG.getNode(ISD::SIGN_EXTEND, ...)
        // In GlobalISel: MIRBuilder.buildSExt(...)
      }

      // Record the mapping: formal argument i -> virtual register VReg
      (void)PhysReg; (void)RegVT;
    } else {
      // Argument on the stack.
      unsigned Offset = VA.getLocMemOffset();
      unsigned Size   = VA.getValVT().getSizeInBits() / 8;

      // Create a stack slot:
      //   int FrameIdx = MFI.CreateFixedObject(Size, Offset, /*Immutable=*/true);
      //   SDValue FrameNode = DAG.getFrameIndex(FrameIdx, PtrTy);
      //   MachinePointerInfo PtrInfo = MachinePointerInfo::getFixedStack(MF, FrameIdx);
      //   SDValue Load = DAG.getLoad(ValVT, DL, Chain, FrameNode, PtrInfo);

      (void)Offset; (void)Size;
    }
  }
}

// ============================================================
// 6. Structure Return Demotion (sret)
// ============================================================

void sretDemotionExample() {
  // Problem: A function returns a large struct that doesn't fit in registers.
  //   struct Big { int field[20]; };
  //   Big callee();

  // Without sret:
  //   Big callee() { ... return result; }
  // The compiler must fit Big into registers -> impossible.

  // With sret demotion:
  //   void callee(Big* sret_ptr) { ... *sret_ptr = result; }
  // The caller allocates stack space and passes a pointer.
  // The callee writes the return value through the pointer.

  // How to check (in TargetLowering or CallLowering):
  //   bool CanLowerReturn = CCInfo.CheckReturn(Outs, CC_XXX);
  //   if (!CanLowerReturn) {
  //     // Demote: add a pointer parameter at position 0
  //     // The pointer gets the sret attribute in LLVM IR
  //     insertSRetIncomingArgument(...);
  //   }

  // The sret pointer is treated as an extra formal argument
  // at index 0 on the callee side.
}

// ============================================================
// 7. Custom SDNode descriptions for call/return (TableGen side)
// ============================================================

// These would be in your XXXInstrInfo.td file:
//
//   def XXXcall : SDNode<"XXXISD::CALL",
//     SDTypeProfile<0, -1, [SDTCisPtrTy<0>]>,
//     [SDNPHasChain, SDNPOptInGlue, SDNPOutGlue, SDNPVariadic]>;
//
//   def XXXret : SDNode<"XXXISD::RET_FLAG",
//     SDTypeProfile<0, 1, [SDTCisVT<0, OtherVT>]>,
//     [SDNPHasChain, SDNPOptInGlue, SDNPVariadic]>;
//
// In C++, expose the enum:
//   namespace XXXISD {
//     enum NodeType : unsigned {
//       FIRST_NUMBER = ISD::BUILTIN_OP_END,
//       CALL,
//       RET_FLAG,
//     };
//   }

void explainCustomSDNodes() {
  // Custom SDNodes are used because SDISel does not provide generic
  // CALL/RET opcodes -- they are too target-specific.

  // Properties explained:
  //   SDNPHasChain  : Takes and produces a chain (ordering dep)
  //   SDNPOptInGlue : Optionally takes glue input
  //   SDNPOutGlue   : Produces a glue output
  //   SDNPVariadic  : Variable number of arguments

  // ISD::CALLSEQ_START / ISD::CALLSEQ_END are special:
  //   The infrastructure already knows about them.
  //   You still need to describe them in TableGen for your target,
  //   but no custom C++ enum is needed.
  //   They bracket call sequences and carry frame size info.
}

// ============================================================
// 8. Stack location handling
// ============================================================

void handleStackLocations() {
  // When CCValAssign.isMemLoc() == true:
  //
  // unsigned Offset = VA.getLocMemOffset();
  // unsigned Size   = VA.getValVT().getSizeInBits() / 8;
  //
  // // Create a fixed stack object (frame index)
  // int FrameIdx = MFI.CreateFixedObject(Size, Offset, /*Immutable=*/true);
  //
  // // Create frame index node
  // SDValue FrameIdxNode = DAG.getFrameIndex(FrameIdx, PtrTy);
  //
  // // Create MachinePointerInfo for memory operands
  // MachinePointerInfo PtrInfo =
  //     MachinePointerInfo::getFixedStack(MF, FrameIdx);
  //
  // // On callee side (formal arguments): LOAD from the stack
  // SDValue Load = DAG.getLoad(ValVT, DL, Chain, FrameIdxNode, PtrInfo);
  //
  // // On caller side (call operands): STORE to the stack
  // SDValue Store = DAG.getStore(Chain, DL, ArgVal, FrameIdxNode, PtrInfo);
}

// ============================================================
// 9. GlobalISel: Assigner + Handler pattern
// ============================================================

// In GlobalISel, ABI lowering uses the assigner + handler pattern:
//
// Assigner (CallLowering::ValueAssigner):
//   - Uses CCAssignFn to determine locations
//   - Subclasses: IncomingValueAssigner, OutgoingValueAssigner
//
// Handler (CallLowering::ValueHandler):
//   - Materializes the assigned locations into MIR instructions
//   - Subclasses: IncomingValueHandler, OutgoingValueHandler
//
// Handler methods to override:
//   assignValueToReg(ValVReg, PhysReg, VA)     // Copy from/to phys reg
//   assignValueToAddress(ValVReg, Addr, MemTy, MPO, VA) // Load/Store
//   getStackAddress(...)                        // Frame index for stack slot
//   getStackValueStoreType(...)                 // LLT for memory op

void globalISelAssignerHandlerPattern() {
  // Workflow in CallLowering::lowerFormalArguments:
  //
  // 1. Create assigner with CCAssignFn:
  //    IncomingValueAssigner Assigner(CC_H2BLB_Common);
  //
  // 2. Create handler:
  //    IncomingArgHandler Handler(MIRBuilder, MRI);
  //
  // 3. Build ArgInfo list from function arguments:
  //    splitToValueTypes(OrigArg, SplitArgs, DL, CC);
  //
  // 4. Run assignment and materialization:
  //    determineAssignments(Assigner, SplitArgs, CCInfo);
  //    handleAssignments(Handler, SplitArgs, CCInfo, ArgLocs, MIRBuilder);

  // The handler takes care of:
  //   - Register locations: updating live-ins, building copies
  //   - Stack locations: creating frame indices, building loads
  //   - Extension/conversion: applying SExt/ZExt/Trunc as needed
}
