// selection_patterns.cpp - Selection Patterns and TableGen Integration
//
// Demonstrates:
//   - TableGen selection patterns (Pat, PatFrag, ComplexPattern)
//   - SDISel Instruction Selection (SelectionDAGISel::Select, SelectCode)
//   - Custom inserters
//   - FastISel pattern matching
//   - GlobalISel InstructionSelector
//   - Importing SDISel patterns into GlobalISel

#include <cassert>
#include <cstdint>
#include <string>
#include <vector>

// ============================================================
// 1. TableGen Selection Patterns (conceptual)
// ============================================================

// Patterns are written in .td files using the Pat class.
// They describe: (input_dag) -> (output_dag)

// --- Example .td pattern definitions ---

/*
// Simple pattern: integer addition
def : Pat<(add i16:$src1, i16:$src2),
          (ADD16 $src1, $src2)>;

// Pattern with immediate operand
def : Pat<(add i16:$src, (i16 imm:$imm)),
          (ADD16i $src, imm:$imm)>;

// Pattern with complex matching (calls C++ function)
def : Pat<(add i16:$src1, (i16 (load i16:$addr))),
          (ADD16rm $src1, i16:$addr)>;

// Using PatFrag for reusable fragments
def zextloadi16 : PatFrag<(ops node:$ptr),
                          (i16 (zextloadi8 node:$ptr))>;
def : Pat<(add i16:$src, (i16 (zextloadi8 i16:$addr))),
          (ADD16rm_zext $src, i16:$addr)>;

// Pattern with multiple results
def : Pat<(i32 (anyext (i16 (add i16:$src1, i16:$src2)))),
          (ADD16_widen $src1, $src2)>;  // Produces i32 result
*/

// ============================================================
// 2. Pattern Classes in TableGen
// ============================================================

struct TableGenPatternClasses {
  // Pat: Basic pattern.
  //   (input_pattern) -> (output_pattern)
  //   Input matches IR instructions; output is the target instruction.

  // PatFrag: Reusable pattern fragment.
  //   def zextload_i16 : PatFrag<(ops node:$ptr),
  //                               (i16 (zextloadi8 node:$ptr))>;
  //   Used in other patterns as: (zextload_i16 $addr)

  // PatLeaf: Leaf pattern matching constants.
  //   def immZExt6 : PatLeaf<(imm), [{ return isUInt<6>(N->getZExtValue()); }]>;
  //   Used as: (ADD16i $src, immZExt6:$imm)

  // ComplexPattern: C++ function for complex matching logic.
  //   def addrMode : ComplexPattern<i16, 2, "SelectAddrMode", [frameindex]>;
  //   Parameters: <result_type, num_operands, "C++FunctionName", [properties]>
};

// ============================================================
// 3. SDISel Instruction Selection (generated by gen-dag-isel)
// ============================================================

// The gen-dag-isel TableGen backend generates code that looks like:

// What TableGen generates (conceptual):
//
// void XXXDAGToDAGISel::SelectCode(SDNode *N) {
//   switch (N->getOpcode()) {
//   case ISD::ADD: {
//     SDValue N0 = N->getOperand(0);
//     SDValue N1 = N->getOperand(1);
//     // Try to match each pattern for ISD::ADD
//     // ... auto-generated pattern matching code ...
//
//     // Pattern 1: (add i16:$src1, i16:$src2) -> (ADD16 $src1, $src2)
//     if (N0.getValueType() == MVT::i16 && N1.getValueType() == MVT::i16) {
//       SDNode *Result = CurDAG->getMachineNode(H2BLB::ADD16, SDLoc(N),
//                                                MVT::i16, N0, N1);
//       ReplaceNode(N, Result);
//       return;
//     }
//
//     // Pattern 2: (add i16:$src, (i16 imm:$imm)) -> (ADD16i $src, $imm)
//     if (/* N1 is a ConstantSDNode with 16-bit immediate */) {
//       SDNode *Result = CurDAG->getMachineNode(H2BLB::ADD16i, SDLoc(N),
//                                                MVT::i16, N0, N1);
//       ReplaceNode(N, Result);
//       return;
//     }
//     break;
//   }
//   // ... Cases for all other ISD opcodes ...
//   }
// }

// ============================================================
// 4. Custom Inserters (SDNodeXForm)
// ============================================================

// Some patterns need custom C++ code AFTER the match succeeds.
// This is done via SDNodeXForm in TableGen and methods on DAGToDAGISel.

/*
// TableGen:
def LO16 : SDNodeXForm<imm, [{
  return CurDAG->getTargetConstant(N->getZExtValue() & 0xFFFF, SDLoc(N), MVT::i16);
}]>;

def : Pat<(add i16:$src, (LO16 imm:$imm)),
          (ADD16i $src, (LO16 imm:$imm))>;

// C++ side (in your DAGToDAGISel class):
void XXXDAGToDAGISel::Select_ISD_ADD(SDNode *N) {
  // Complex selection logic that can't be expressed in TableGen
  // e.g., checking instruction properties, register constraints, etc.
}
*/

// ============================================================
// 5. FastISel Selection
// ============================================================

class FastISelExample {
public:
  // FastISel does everything in one step.
  // It must:
  //   1. Check if the target lowering says "fall back to DAG ISel"
  //   2. Try custom selection via switch on LLVM IR opcode
  //   3. Fall back to TableGen-generated patterns (selectOperator)

  bool fastSelectInstruction(/* const Instruction *I */) {
    // // Step 1: Check fallback condition
    // if (TLI.fallBackToDAGISel(*I))
    //   return false;
    //
    // // Step 2: Custom selection
    // switch (I->getOpcode()) {
    // case Instruction::Add:
    //   return selectAdd(I);
    // case Instruction::Call:
    //   return selectCall(I);
    // case Instruction::Ret:
    //   return selectRet(I);
    // default:
    //   break;
    // }
    //
    // // Step 3: TableGen-generated selection
    // // (Generated by gen-fast-isel backend)
    // return selectOperator(I, I->getOpcode());

    return false;
  }

  // The SkipTargetIndependentISel flag controls order:
  //   true  -> custom code first, then TableGen patterns
  //   false -> TableGen patterns first, then custom code
  // Both approaches are valid.

  // Key: must call updateValueMap(Value*, Register) for each
  // lowered LLVM IR value, so SDISel knows about it in case of fallback.
};

// ============================================================
// 6. GlobalISel InstructionSelector
// ============================================================

class XXXInstructionSelector {
public:
  // The main selection entry point.
  // Called for each MachineInstr in the function.
  // Returns true if the instruction was selected, false otherwise.

  bool select(/* MachineInstr &I */) {
    // // Step 1: Try TableGen-imported patterns
    // if (selectImpl(I, *CoverageInfo))
    //   return true;  // Pattern matched and instruction replaced
    //
    // // Step 2: Manual selection for instructions not covered by patterns
    // switch (I.getOpcode()) {
    // case TargetOpcode::G_ADD:
    //   return selectG_ADD(I);
    // case TargetOpcode::G_LOAD:
    //   return selectG_LOAD(I);
    // case TargetOpcode::G_BRCOND:
    //   return selectG_BRCOND(I);
    // default:
    //   return false;  // Could not select -> error or fallback
    // }

    return true;
  }

  // Manual selection example: G_ADD -> target ADD instruction
  bool selectG_ADD(/* MachineInstr &I */) {
    // Register Dst = I.getOperand(0).getReg();
    // Register Src1 = I.getOperand(1).getReg();
    // Register Src2 = I.getOperand(2).getReg();
    //
    // // Choose the right target instruction based on type
    // LLT Ty = MRI.getType(Dst);
    // unsigned TargetOpc;
    // if (Ty == LLT::scalar(16))
    //   TargetOpc = H2BLB::ADD16;
    // else if (Ty == LLT::scalar(32))
    //   TargetOpc = H2BLB::ADD32;
    //
    // // Morph the instruction
    // I.setDesc(TII.get(TargetOpc));
    //
    // // Constrain register operands (sets register classes, inserts copies)
    // return constrainSelectedInstRegOperands(I, TII, TRI, RBI);
    return true;
  }

  // The constrainSelectedInstRegOperands function is CRITICAL:
  // - Sets register class for each register operand
  // - Creates COPY instructions if register doesn't match the class
  // - Required to produce well-formed target-specific MIR
};

// ============================================================
// 7. Importing SDISel Patterns into GlobalISel
// ============================================================

void importPatternsExample() {
  // GlobalISel can import SDISel's TableGen patterns using GlobalISelEmitter.
  //
  // In CMakeLists.txt:
  //   tablegen(LLVM XXXGenGlobalISel.inc -gen-global-isel
  //            -warn-on-skipped-patterns)
  //
  // The -warn-on-skipped-patterns flag reports which SDISel patterns
  // could not be imported (due to fundamental differences between the
  // two frameworks).
  //
  // In your InstructionSelector:
  //   #include "XXXGenGlobalISel.inc"
  //   bool select(MachineInstr &I) override {
  //     if (selectImpl(I, *CoverageInfo))  // Generated by GlobalISelEmitter
  //       return true;
  //     return selectCustom(I);
  //   }
  //
  // Limitations:
  //   - Not all SDISel patterns can be imported (e.g., complex SDNodeXForm).
  //   - The fallback is manual C++ selection.
  //   - CoverageInfo tracks which patterns were used for statistics.
}

// ============================================================
// 8. Pattern Matching Utilities in GlobalISel
// ============================================================

void globalISelPatternMatching() {
  // GlobalISel provides the mi_match utility (from MIPatternMatch.h)
  // for pattern matching on G_MIR:
  //
  //   #include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
  //   using namespace llvm::MIPatternMatch;
  //
  // Pattern matchers:
  //   m_GAdd(m_Reg(LHS), m_Reg(RHS))   -> matches G_ADD
  //   m_GSExt(m_Reg(Src))               -> matches G_SEXT
  //   m_GZExt(m_Reg(Src))               -> matches G_ZEXT
  //   m_GConstInt(m_SpecificInt(42))    -> matches G_CONSTANT with value 42
  //   m_GCst(Cst)                       -> matches G_CONSTANT, captures value
  //   m_GLoad(m_Reg(Ptr))               -> matches G_LOAD
  //   m_GTrunc(m_Reg(Src))              -> matches G_TRUNC
  //
  // Example:
  //   Register PlainLHS, PlainRHS;
  //   if (mi_match(LHSReg, MRI, m_GSExt(m_Reg(PlainLHS))) &&
  //       mi_match(RHSReg, MRI, m_GSExt(m_Reg(PlainRHS)))) {
  //     // Both operands are G_SEXT results
  //     // PlainLHS and PlainRHS hold the source registers
  //   }
  //
  // SDISel added similar utilities (sd_match) since Feb 2024.
}

// ============================================================
// 9. Summary: Selection Pattern Workflow
// ============================================================

void selectionPatternWorkflow() {
  // For each instruction in the selection phase:

  // SDISel:
  //   for each SDNode in DAG:
  //     -> Select(SDNode*)
  //       -> if isMachineOpcode(), skip
  //       -> SelectCode(N)  // TableGen-generated switch
  //         -> tries each pattern for this opcode
  //         -> first match wins
  //         -> ReplaceNode(Old, NewMachineNode)
  //       -> if no match, SDNode remains -> error or later abort

  // FastISel:
  //   for each LLVM IR Instruction in BB:
  //     -> fastSelectInstruction(I)
  //       -> custom switch on I->getOpcode()
  //       -> fallback to selectOperator() (TableGen-generated)
  //       -> if fails, fallback to SDISel (per-BB or full)

  // GlobalISel:
  //   for each MachineInstr in MF:
  //     -> select(MI)
  //       -> selectImpl(MI)  // Imported SDISel patterns
  //       -> switch on MI.getOpcode()  // Manual selection
  //       -> morph MI (setDesc, set operands)
  //       -> constrainSelectedInstRegOperands()
}
