add_executable(10_baseline baseline.cpp)
target_link_libraries(10_baseline PRIVATE oopt_common)
add_executable(10_optimized optimized.cpp)
target_link_libraries(10_optimized PRIVATE oopt_common)
add_executable(10_benchmark benchmark.cpp)
target_link_libraries(10_benchmark PRIVATE oopt_common)
find_package(Threads REQUIRED)
target_link_libraries(10_baseline PRIVATE Threads::Threads)
target_link_libraries(10_optimized PRIVATE Threads::Threads)
target_link_libraries(10_benchmark PRIVATE Threads::Threads)
