// iselframeworks.cpp - Concepts of FastISel, SDISel, GlobalISel frameworks
//
// This file illustrates the high-level patterns used by the three instruction
// selection frameworks in LLVM. It does NOT compile as-is; it demonstrates the
// architecture and key APIs used when implementing a backend.

#include <cassert>
#include <memory>
#include <vector>

// --- Simulated LLVM types (abbreviated) ---

// Generic opcode identifiers
enum class ISDOpcode : unsigned {
  ADD, SUB, MUL, LOAD, STORE, CopyFromReg, CopyToReg,
  BUILD_VECTOR, EXTRACT_VECTOR_ELT, // ... many more
};

// G_MIR (Generic Machine IR) opcodes
enum class GenericOpcode : unsigned {
  G_ADD, G_SUB, G_MUL, G_LOAD, G_STORE,
  G_CONSTANT, G_SEXT, G_ZEXT, G_IMPLICIT_DEF, G_PHI,
};

// Target-specific opcodes
struct TargetOpcode {
  static constexpr unsigned PHI = 0;
  static constexpr unsigned COPY = 1;
};

// Value type simulation
struct MVT {
  unsigned SizeInBits;
  static MVT i16() { return {16}; }
  static MVT i32() { return {32}; }
  static MVT Other() { return {0}; }   // Represents chain/glue
};

// Register
using Register = unsigned;
static constexpr Register NoRegister = 0;

// MachineInstr stub (simplified)
struct MachineInstr {
  unsigned getOpcode() const { return Opcode; }
  unsigned Opcode;
  // ... operands, debug loc, etc.
};

// SDNode stub (simplified)
struct SDNode {
  unsigned getOpcode() const { return Opcode; }
  bool isMachineOpcode() const { return IsMachine; }
  unsigned Opcode;
  bool IsMachine = false;
};

struct SDValue {
  SDNode* Node;
  unsigned ResNo;
  SDValue() : Node(nullptr), ResNo(0) {}
};

// --- Framework 1: SDISel (SelectionDAG) ---

// The SelectionDAGISel class is a MachineFunctionPass.
// Each backend subclasses it:
class XXXDAGToDAGISel : public /* SelectionDAGISel */ /* ... */ {
public:
  // Core selection entry point. Called once per SDNode.
  void Select(SDNode *N) {
    // Bail out if already a machine opcode (target instruction)
    if (N->isMachineOpcode())
      return;

    // SelectCode is auto-generated by TableGen (gen-dag-isel backend).
    // It contains a giant switch over ISD opcodes dispatching to
    // individual Select_ISD_XXX methods that match patterns.
    // SelectCode(N);
  }

  // Custom selection methods (hand-written or TableGen-generated):
  // void Select_ISD_ADD(SDNode *N);
  // void Select_ISD_LOAD(SDNode *N);

private:
  // Include the auto-generated selection code
  // #include "XXXGenDAGISel.inc"
};

// Helper to create the legacy pass wrapper
class XXXDAGToDAGISelLegacy {
public:
  // static char ID;
  // XXXDAGToDAGISelLegacy(XXXTargetMachine &TM)
  //     : SelectionDAGISelLegacy(ID, std::make_unique<XXXDAGToDAGISel>(TM)) {}
};

// --- Framework 2: FastISel (sub-selector of SDISel) ---

class XXXFastISel : public /* FastISel */ /* ... */ {
public:
  // fastSelectInstruction tries to select a single LLVM IR instruction.
  // It returns true on success, false to trigger fallback to SDISel.
  bool fastSelectInstruction(/* const Instruction *I */) {
    // Check if the target lowering says "fall back to DAG ISel"
    // if (TLI.fallBackToDAGISel(*I))
    //   return false;

    // Try target-specific lowering via switch
    // switch (I->getOpcode()) {
    // case Instruction::Add: return selectAdd(I);
    // default: break;
    // }

    // Fall back to TableGen-generated selection code
    // return selectOperator(I, I->getOpcode());
    return false;
  }

  // Lower formal arguments (ABI) before selection
  bool fastLowerArguments() {
    // For each argument in the function:
    //   - Find which physical register it's passed in
    //   - Create a virtual register with the right register class
    //   - Add live-in mapping via MF.addLiveIn(PhysReg, VRegRC)
    //   - Emit a COPY instruction from virtual src to result vreg
    //   - Call updateValueMap(&Arg, ResultReg)
    return true;
  }

private:
  // #include "XXXGenFastISel.inc"
};

// FastISel is connected to SDISel via TargetLowering:
// FastISel *createFastISel(FunctionLoweringInfo &, const TargetLibraryInfo *) {
//   return new XXXFastISel(...);
// }

// --- Framework 3: GlobalISel ---

// GlobalISel uses a pipeline of standalone MachineFunctionPass instances.
// The four core passes:

// 1. IRTranslator - translates LLVM IR to G_MIR
class IRTranslatorPass {
  // Uses CallLowering hooks to handle ABI.
  // Pass hook: bool runOnMachineFunction(MachineFunction &MF);
};

// 2. Legalizer - legalizes G_MIR ops/types
class LegalizerPass {
  // Uses LegalizerInfo to determine actions for each (opcode, type) pair.
  // Pass hook: bool runOnMachineFunction(MachineFunction &MF);
};

// 3. RegBankSelect - assigns register banks to virtual registers
class RegBankSelectPass {
  // Uses RegisterBankInfo::getInstrMapping() for each instruction.
  // Optionally rewrites code to minimize cross-register-bank copies.
  // Pass hook: bool runOnMachineFunction(MachineFunction &MF);
};

// 4. InstructionSelect - translates G_MIR to target-specific MIR
class InstructionSelectPass {
  // Uses InstructionSelector::select(MachineInstr &I) for each instruction.
  // After this pass: no G_ opcodes, no generic vregs remain.
  // Pass hook: bool runOnMachineFunction(MachineFunction &MF);
};

// Connecting GlobalISel passes in TargetPassConfig:
class XXXPassConfig {
  bool addIRTranslator() {
    // addPass(new IRTranslator(getOptLevel()));
    return false;
  }
  bool addLegalizeMachineIR() {
    // addPass(new Legalizer());
    return false;
  }
  bool addRegBankSelect() {
    // addPass(new RegBankSelect());
    return false;
  }
  bool addGlobalInstructionSelect() {
    // addPass(new InstructionSelect(getOptLevel()));
    return false;
  }
};

// --- Selector fallback demonstration ---

// The fallback mechanism between selectors:
void demonstrateFallback() {
  // GlobalISel tries first. If it fails:
  //   1. ResetMachineFunction pass resets the MachineFunction state.
  //   2. SDISel takes over for the whole function.

  // Within SDISel, each basic block:
  //   1. FastISel tries the basic block.
  //   2. If FastISel fails mid-block, SDISel finishes the block.

  // Fallback policies can be controlled by:
  //   - setGlobalISelAbort(0): silent fallback
  //   - setGlobalISelAbort(1): fatal error on fallback
  //   - setGlobalISelAbort(2): fallback with warning
  // CLI: -global-isel-abort=0|1|2
}
