cmake_minimum_required(VERSION 3.8)
project(ros2_loaned_image)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(sensor_msgs REQUIRED)
add_executable(loaned_image_nodes src/loaned_image_nodes.cpp)
target_compile_features(loaned_image_nodes PUBLIC cxx_std_17)
ament_target_dependencies(loaned_image_nodes rclcpp sensor_msgs)
install(TARGETS loaned_image_nodes DESTINATION lib/${PROJECT_NAME})
ament_package()
