# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

# 此文件由 FlatBuffers 编译器 (flatc) 根据 TFLite schema 自动生成，请勿手动修改。
# 
# FlatBuffers 设计原理
# ═══════════════════
# TFLite 使用 Google FlatBuffers 作为模型序列化格式。相比 Protocol Buffers：
#   1. 零拷贝反序列化 — 无需解析即可直接读取二进制数据，CPU/内存开销极低
#   2. 按需字段访问 — vtable（虚表）机制，只读取需要的字段，不浪费
#   3. 紧凑二进制格式 — 文件体积小，适合 MCU 等资源受限设备
# 
# 文件结构
# ════════
# 本文件定义了 TFLite schema 中对应表的 Python 绑定类，包含：
#   - 读取部分：GetRootAsXxx / Init / 各字段访问器方法
#   - 写入部分：StartXxx / AddXxx / EndXxx 构建器函数（用于创建新的 FlatBuffer）
# 
# 字段访问模式
# ══════════════
# 每个访问器方法的实现遵循固定模式：
#   o = Offset(vtable_slot)  ← 通过 vtable 查找字段在 buffer 中的偏移
#   if o != 0:               ← o==0 表示字段未设置（该字段在模型中不存在）
#     return ReadData(o)     ← 从 buffer 的偏移位置读取数据
#   return default_value     ← 字段不存在时返回默认值
# 
# 此包被 TfliteConvertor.py 在编译管线中调用，将 .tflite 模型文件解析为 TinyEngine IR。

# ============================================================
# Model — TFLite 模型根节点
# ============================================================

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Model(object):
# _tab 是 FlatBuffers Table 访问器，保存了该表在二进制 buffer 中的位置引用
# 所有字段访问都通过 self._tab 进行 vtable 查找
    __slots__ = ['_tab']

# ============================================================
# FlatBuffer 根节点解析入口
# 从内存中的 FlatBuffer 二进制数据中解析出 Model 表
# 调用方式: obj = Model.GetRootAsModel(buf, offset)
#   - buf: bytes 类型，整个 FlatBuffer 二进制数据
#   - offset: 起始偏移量（通常为 0）
# TfliteConvertor.loadTFmodel() 通过 Model.GetRootAsModel(buf, 0) 调用
# ============================================================
    @classmethod
# 读取 uoffset（无符号偏移）值，这是 FlatBuffer 根表的起始位置
    def GetRootAsModel(cls, buf, offset):
# 从 buffer 中编码的 uoffset 偏移处开始解析根对象
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
# 创建表对象实例并初始化
        x = Model()
# Init 将 x._tab 绑定到 buffer 中的实际数据位置
        x.Init(buf, n + offset)
# 返回解析后的对象
        return x

# ------------------------------------------------------------
# 检查 buffer 是否包含有效的 TFLite 文件标识符
# 'TFL3' 魔术字 (0x54 0x46 0x4C 0x33) 是 TFLite 文件的签名
# 用于验证文件是否为有效的 FlatBuffer TFLite 模型
# ------------------------------------------------------------
    @classmethod
    def ModelBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
# flatbuffers.util.BufferHasIdentifier 内部实现二进制签名比对
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # Model
# ------------------------------------------------------------
# 初始化 Model 表对象
# self._tab 是 flatbuffers.table.Table 实例，封装了对 FlatBuffer 二进制数据的访问
# buf: 完整的 FlatBuffer 二进制数据（bytes）
# pos: 该表在 buf 中的起始位置偏移
# 所有后续的字段访问器方法都通过 self._tab 进行 vtable 查找
# ------------------------------------------------------------
    def Init(self, buf, pos):
# 将 Table 访问器绑定到 buf 的 pos 位置
        self._tab = flatbuffers.table.Table(buf, pos)

    # Model
# 读取 Version 字段（uint32（无符号32位整数））
# 模型格式版本号（uint32）
# vtable 偏移量: 4，对应 schema 中第 0 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def Version(self):
# 通过 vtable 偏移 4 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 uint32（无符号32位整数） 值
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # Model
# 读取 OperatorCodes 向量字段（子表对象数组）
# 算子代码表（OperatorCode 列表），每个 entry 将整数 BuiltinCode 映射到具体算子类型
# vtable 偏移量: 6
    def OperatorCodes(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# 每个元素占 4 字节（uoffset 指针），加上 j 偏移指向第 j 个元素
        if o != 0:
# Indirect 解引用到实际子表的起始位置
            x = self._tab.Vector(o)
# 导入对应的子表类（延迟导入，避免循环依赖）
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
# 创建子表对象并绑定到 buffer 中的对应位置
            x = self._tab.Indirect(x)
# 初始化子表
            from .OperatorCode import OperatorCode
# 返回子表对象
            obj = OperatorCode()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
# 返回 OperatorCodes 向量的长度（元素个数）
# vtable 偏移量: 6
    def OperatorCodesLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
# 读取 OperatorCodesIsNone 向量字段（标量 数组）
# 算子代码表（OperatorCode 列表），每个 entry 将整数 BuiltinCode 映射到具体算子类型
# vtable 偏移量: 6
    def OperatorCodesIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # Model
# 读取 Subgraphs 向量字段（子表对象数组）
# 子图列表。TinyEngine 使用 Subgraphs(0) 获取主执行图
# vtable 偏移量: 8
    def Subgraphs(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# 每个元素占 4 字节（uoffset 指针），加上 j 偏移指向第 j 个元素
        if o != 0:
# Indirect 解引用到实际子表的起始位置
            x = self._tab.Vector(o)
# 导入对应的子表类（延迟导入，避免循环依赖）
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
# 创建子表对象并绑定到 buffer 中的对应位置
            x = self._tab.Indirect(x)
# 初始化子表
            from .SubGraph import SubGraph
# 返回子表对象
            obj = SubGraph()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
# 返回 Subgraphs 向量的长度（元素个数）
# vtable 偏移量: 8
    def SubgraphsLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
# 读取 SubgraphsIsNone 字段（字符串类型）
# 子图列表。TinyEngine 使用 Subgraphs(0) 获取主执行图
# vtable 偏移量: 8
    def SubgraphsIsNone(self):
# String(offset) 返回 buffer 中该偏移处的 UTF-8 字符串
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0
# return self._tab.String(...) = 读取字符串

# 字段不存在时返回 None
    # Model
# 读取 Description 字段（字符串类型）
# 模型描述字符串（UTF-8）
# vtable 偏移量: 10
    def Description(self):
# String(offset) 返回 buffer 中该偏移处的 UTF-8 字符串
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
# return self._tab.String(...) = 读取字符串
            return self._tab.String(o + self._tab.Pos)
# 字段不存在时返回 None
        return None

    # Model
# 读取 Buffers 向量字段（子表对象数组）
# 权重/偏置等持久化数据的缓冲区列表。Tensor.Buffer 索引指向此列表
# vtable 偏移量: 12
    def Buffers(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
# 每个元素占 4 字节（uoffset 指针），加上 j 偏移指向第 j 个元素
        if o != 0:
# Indirect 解引用到实际子表的起始位置
            x = self._tab.Vector(o)
# 导入对应的子表类（延迟导入，避免循环依赖）
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
# 创建子表对象并绑定到 buffer 中的对应位置
            x = self._tab.Indirect(x)
# 初始化子表
            from .Buffer import Buffer
# 返回子表对象
            obj = Buffer()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
# 返回 Buffers 向量的长度（元素个数）
# vtable 偏移量: 12
    def BuffersLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
# 读取 BuffersIsNone 向量字段（标量 数组）
# 权重/偏置等持久化数据的缓冲区列表。Tensor.Buffer 索引指向此列表
# vtable 偏移量: 12
    def BuffersIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # Model
# 读取 MetadataBuffer 向量字段（int32（有符号32位整数） 数组）
# 元数据缓冲区索引的向量
# vtable 偏移量: 14
    def MetadataBuffer(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Model
# 以 Numpy ndarray 形式返回 MetadataBuffer 向量的全部元素
# vtable 偏移量: 14
    def MetadataBufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Model
# 返回 MetadataBuffer 向量的长度（元素个数）
# vtable 偏移量: 14
    def MetadataBufferLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
# 读取 MetadataBufferIsNone 向量字段（标量 数组）
# 元数据缓冲区索引的向量
# vtable 偏移量: 14
    def MetadataBufferIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # Model
# 读取 Metadata 向量字段（子表对象数组）
# 元数据键值对列表（名称 + 缓冲区索引）
# vtable 偏移量: 16
    def Metadata(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
# 每个元素占 4 字节（uoffset 指针），加上 j 偏移指向第 j 个元素
        if o != 0:
# Indirect 解引用到实际子表的起始位置
            x = self._tab.Vector(o)
# 导入对应的子表类（延迟导入，避免循环依赖）
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
# 创建子表对象并绑定到 buffer 中的对应位置
            x = self._tab.Indirect(x)
# 初始化子表
            from .Metadata import Metadata
# 返回子表对象
            obj = Metadata()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
# 返回 Metadata 向量的长度（元素个数）
# vtable 偏移量: 16
    def MetadataLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
# 读取 MetadataIsNone 向量字段（标量 数组）
# 元数据键值对列表（名称 + 缓冲区索引）
# vtable 偏移量: 16
    def MetadataIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # Model
# 读取 SignatureDefs 向量字段（子表对象数组）
# 签名定义列表（多入口/出口模型的输入输出映射）
# vtable 偏移量: 18
    def SignatureDefs(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
# 每个元素占 4 字节（uoffset 指针），加上 j 偏移指向第 j 个元素
        if o != 0:
# Indirect 解引用到实际子表的起始位置
            x = self._tab.Vector(o)
# 导入对应的子表类（延迟导入，避免循环依赖）
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
# 创建子表对象并绑定到 buffer 中的对应位置
            x = self._tab.Indirect(x)
# 初始化子表
            from .SignatureDef import SignatureDef
# 返回子表对象
            obj = SignatureDef()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Model
# 返回 SignatureDefs 向量的长度（元素个数）
# vtable 偏移量: 18
    def SignatureDefsLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Model
# 读取 SignatureDefsIsNone 向量字段（标量 数组）
# 签名定义列表（多入口/出口模型的输入输出映射）
# vtable 偏移量: 18
    def SignatureDefsIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

def ModelStart(builder): builder.StartObject(8)
def ModelAddVersion(builder, version): builder.PrependUint32Slot(0, version, 0)
def ModelAddOperatorCodes(builder, operatorCodes): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(operatorCodes), 0)
def ModelStartOperatorCodesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ModelAddSubgraphs(builder, subgraphs): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(subgraphs), 0)
def ModelStartSubgraphsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ModelAddDescription(builder, description): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(description), 0)
def ModelAddBuffers(builder, buffers): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(buffers), 0)
def ModelStartBuffersVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ModelAddMetadataBuffer(builder, metadataBuffer): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(metadataBuffer), 0)
def ModelStartMetadataBufferVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ModelAddMetadata(builder, metadata): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)
def ModelStartMetadataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ModelAddSignatureDefs(builder, signatureDefs): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(signatureDefs), 0)
def ModelStartSignatureDefsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ModelEnd(builder): return builder.EndObject()