# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

# 此文件由 FlatBuffers 编译器 (flatc) 根据 TFLite schema 自动生成，请勿手动修改。
# 
# FlatBuffers 设计原理
# ═══════════════════
# TFLite 使用 Google FlatBuffers 作为模型序列化格式。相比 Protocol Buffers：
#   1. 零拷贝反序列化 — 无需解析即可直接读取二进制数据，CPU/内存开销极低
#   2. 按需字段访问 — vtable（虚表）机制，只读取需要的字段，不浪费
#   3. 紧凑二进制格式 — 文件体积小，适合 MCU 等资源受限设备
# 
# 文件结构
# ════════
# 本文件定义了 TFLite schema 中对应表的 Python 绑定类，包含：
#   - 读取部分：GetRootAsXxx / Init / 各字段访问器方法
#   - 写入部分：StartXxx / AddXxx / EndXxx 构建器函数（用于创建新的 FlatBuffer）
# 
# 字段访问模式
# ══════════════
# 每个访问器方法的实现遵循固定模式：
#   o = Offset(vtable_slot)  ← 通过 vtable 查找字段在 buffer 中的偏移
#   if o != 0:               ← o==0 表示字段未设置（该字段在模型中不存在）
#     return ReadData(o)     ← 从 buffer 的偏移位置读取数据
#   return default_value     ← 字段不存在时返回默认值
# 
# 此包被 TfliteConvertor.py 在编译管线中调用，将 .tflite 模型文件解析为 TinyEngine IR。

# ============================================================
# Operator — 算子节点（一个计算操作）
# ============================================================

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Operator(object):
# _tab 是 FlatBuffers Table 访问器，保存了该表在二进制 buffer 中的位置引用
# 所有字段访问都通过 self._tab 进行 vtable 查找
    __slots__ = ['_tab']

# ============================================================
# FlatBuffer 根节点解析入口
# 从内存中的 FlatBuffer 二进制数据中解析出 Operator 表
# 调用方式: obj = Operator.GetRootAsOperator(buf, offset)
#   - buf: bytes 类型，整个 FlatBuffer 二进制数据
#   - offset: 起始偏移量（通常为 0）
# TfliteConvertor.loadTFmodel() 通过 Operator.GetRootAsOperator(buf, 0) 调用
# ============================================================
    @classmethod
# 读取 uoffset（无符号偏移）值，这是 FlatBuffer 根表的起始位置
    def GetRootAsOperator(cls, buf, offset):
# 从 buffer 中编码的 uoffset 偏移处开始解析根对象
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
# 创建表对象实例并初始化
        x = Operator()
# Init 将 x._tab 绑定到 buffer 中的实际数据位置
        x.Init(buf, n + offset)
# 返回解析后的对象
        return x

# ------------------------------------------------------------
# 检查 buffer 是否包含有效的 TFLite 文件标识符
# 'TFL3' 魔术字 (0x54 0x46 0x4C 0x33) 是 TFLite 文件的签名
# 用于验证文件是否为有效的 FlatBuffer TFLite 模型
# ------------------------------------------------------------
    @classmethod
    def OperatorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
# flatbuffers.util.BufferHasIdentifier 内部实现二进制签名比对
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # Operator
# ------------------------------------------------------------
# 初始化 Operator 表对象
# self._tab 是 flatbuffers.table.Table 实例，封装了对 FlatBuffer 二进制数据的访问
# buf: 完整的 FlatBuffer 二进制数据（bytes）
# pos: 该表在 buf 中的起始位置偏移
# 所有后续的字段访问器方法都通过 self._tab 进行 vtable 查找
# ------------------------------------------------------------
    def Init(self, buf, pos):
# 将 Table 访问器绑定到 buf 的 pos 位置
        self._tab = flatbuffers.table.Table(buf, pos)

    # Operator
# 读取 OpcodeIndex 字段（uint32（无符号32位整数））
# 算子类型在 Model.OperatorCodes 列表中的索引
# vtable 偏移量: 4，对应 schema 中第 0 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def OpcodeIndex(self):
# 通过 vtable 偏移 4 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 uint32（无符号32位整数） 值
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # Operator
# 读取 Inputs 向量字段（int32（有符号32位整数） 数组）
# 输入张量索引列表（int32 向量），指向 SubGraph.Tensors
# vtable 偏移量: 6
    def Inputs(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Operator
# 以 Numpy ndarray 形式返回 Inputs 向量的全部元素
# vtable 偏移量: 6
    def InputsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Operator
# 返回 Inputs 向量的长度（元素个数）
# vtable 偏移量: 6
    def InputsLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operator
# 读取 InputsIsNone 向量字段（标量 数组）
# 输入张量索引列表（int32 向量），指向 SubGraph.Tensors
# vtable 偏移量: 6
    def InputsIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # Operator
# 读取 Outputs 向量字段（int32（有符号32位整数） 数组）
# 输出张量索引列表（int32 向量），指向 SubGraph.Tensors
# vtable 偏移量: 8
    def Outputs(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Operator
# 以 Numpy ndarray 形式返回 Outputs 向量的全部元素
# vtable 偏移量: 8
    def OutputsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Operator
# 返回 Outputs 向量的长度（元素个数）
# vtable 偏移量: 8
    def OutputsLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operator
# 读取 OutputsIsNone 字段（标量）
# 输出张量索引列表（int32 向量），指向 SubGraph.Tensors
# vtable 偏移量: 8，对应 schema 中第 2 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def OutputsIsNone(self):
# 通过 vtable 偏移 8 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        return o == 0
# 从 buffer 的 (o + self._tab.Pos) 处读取 标量 值

# 字段不存在/未设置时返回默认值
    # Operator
# 读取 BuiltinOptionsType 字段（uint8（无符号8位整数））
# 内置参数的类型枚举（BuiltinOptions），决定如何解析 BuiltinOptions
# vtable 偏移量: 10，对应 schema 中第 3 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def BuiltinOptionsType(self):
# 通过 vtable 偏移 10 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 uint8（无符号8位整数） 值
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # Operator
# 读取 BuiltinOptions 字段（Union 联合体类型）
# 内置算子参数（Union 联合体，需根据 BuiltinOptionsType 转换为具体 Options 表）
# vtable 偏移量: 12
# 需要配合对应的 Type 枚举字段确定联合体的具体类型
    def BuiltinOptions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
# Union 类型: 创建一个空的 Table 对象，然后通过 Union() 方法填充内容
            from flatbuffers.table import Table
# 返回的 Table 对象需要根据 Type 枚举转换为具体类型
            obj = Table(bytearray(), 0)
# 字段不存在时返回 None
            self._tab.Union(obj, o)
            return obj
        return None

    # Operator
# 读取 CustomOptions 向量字段（uint8（无符号8位整数） 数组）
# 自定义算子的原始参数字节（uint8 向量）
# vtable 偏移量: 14
    def CustomOptions(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 uint8（无符号8位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Operator
# 以 Numpy ndarray 形式返回 CustomOptions 向量的全部元素
# vtable 偏移量: 14
    def CustomOptionsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Operator
# 返回 CustomOptions 向量的长度（元素个数）
# vtable 偏移量: 14
    def CustomOptionsLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operator
# 读取 CustomOptionsIsNone 字段（标量）
# 自定义算子的原始参数字节（uint8 向量）
# vtable 偏移量: 14，对应 schema 中第 5 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def CustomOptionsIsNone(self):
# 通过 vtable 偏移 14 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        return o == 0
# 从 buffer 的 (o + self._tab.Pos) 处读取 标量 值

# 字段不存在/未设置时返回默认值
    # Operator
# 读取 CustomOptionsFormat 字段（int8（有符号8位整数））
# 自定义选项的编码格式（FLATBUFFERS=0）
# vtable 偏移量: 16，对应 schema 中第 6 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def CustomOptionsFormat(self):
# 通过 vtable 偏移 16 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 int8（有符号8位整数） 值
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # Operator
# 读取 MutatingVariableInputs 向量字段（bool（布尔值） 数组）
# 标记哪些输入张量会被就地修改（bool 向量，训练用）
# vtable 偏移量: 18
    def MutatingVariableInputs(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 bool（布尔值） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.BoolFlags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Operator
# 以 Numpy ndarray 形式返回 MutatingVariableInputs 向量的全部元素
# vtable 偏移量: 18
    def MutatingVariableInputsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.BoolFlags, o)
        return 0

    # Operator
# 返回 MutatingVariableInputs 向量的长度（元素个数）
# vtable 偏移量: 18
    def MutatingVariableInputsLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operator
# 读取 MutatingVariableInputsIsNone 向量字段（标量 数组）
# 标记哪些输入张量会被就地修改（bool 向量，训练用）
# vtable 偏移量: 18
    def MutatingVariableInputsIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # Operator
# 读取 Intermediates 向量字段（int32（有符号32位整数） 数组）
# 中间张量索引列表（优化器/编译器辅助信息）
# vtable 偏移量: 20
    def Intermediates(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Operator
# 以 Numpy ndarray 形式返回 Intermediates 向量的全部元素
# vtable 偏移量: 20
    def IntermediatesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Operator
# 返回 Intermediates 向量的长度（元素个数）
# vtable 偏移量: 20
    def IntermediatesLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operator
# 读取 IntermediatesIsNone 向量字段（标量 数组）
# 中间张量索引列表（优化器/编译器辅助信息）
# vtable 偏移量: 20
    def IntermediatesIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

def OperatorStart(builder): builder.StartObject(9)
def OperatorAddOpcodeIndex(builder, opcodeIndex): builder.PrependUint32Slot(0, opcodeIndex, 0)
def OperatorAddInputs(builder, inputs): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(inputs), 0)
def OperatorStartInputsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OperatorAddOutputs(builder, outputs): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(outputs), 0)
def OperatorStartOutputsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OperatorAddBuiltinOptionsType(builder, builtinOptionsType): builder.PrependUint8Slot(3, builtinOptionsType, 0)
def OperatorAddBuiltinOptions(builder, builtinOptions): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(builtinOptions), 0)
def OperatorAddCustomOptions(builder, customOptions): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(customOptions), 0)
def OperatorStartCustomOptionsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def OperatorAddCustomOptionsFormat(builder, customOptionsFormat): builder.PrependInt8Slot(6, customOptionsFormat, 0)
def OperatorAddMutatingVariableInputs(builder, mutatingVariableInputs): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(mutatingVariableInputs), 0)
def OperatorStartMutatingVariableInputsVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def OperatorAddIntermediates(builder, intermediates): builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(intermediates), 0)
def OperatorStartIntermediatesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OperatorEnd(builder): return builder.EndObject()