# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

# 此文件由 FlatBuffers 编译器 (flatc) 根据 TFLite schema 自动生成，请勿手动修改。
# 
# FlatBuffers 设计原理
# ═══════════════════
# TFLite 使用 Google FlatBuffers 作为模型序列化格式。相比 Protocol Buffers：
#   1. 零拷贝反序列化 — 无需解析即可直接读取二进制数据，CPU/内存开销极低
#   2. 按需字段访问 — vtable（虚表）机制，只读取需要的字段，不浪费
#   3. 紧凑二进制格式 — 文件体积小，适合 MCU 等资源受限设备
# 
# 文件结构
# ════════
# 本文件定义了 TFLite schema 中对应表的 Python 绑定类，包含：
#   - 读取部分：GetRootAsXxx / Init / 各字段访问器方法
#   - 写入部分：StartXxx / AddXxx / EndXxx 构建器函数（用于创建新的 FlatBuffer）
# 
# 字段访问模式
# ══════════════
# 每个访问器方法的实现遵循固定模式：
#   o = Offset(vtable_slot)  ← 通过 vtable 查找字段在 buffer 中的偏移
#   if o != 0:               ← o==0 表示字段未设置（该字段在模型中不存在）
#     return ReadData(o)     ← 从 buffer 的偏移位置读取数据
#   return default_value     ← 字段不存在时返回默认值
# 
# 此包被 TfliteConvertor.py 在编译管线中调用，将 .tflite 模型文件解析为 TinyEngine IR。

# ============================================================
# QuantizationParameters — 张量量化参数（决定浮点数与整数之间的映射关系）
# ============================================================

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuantizationParameters(object):
# _tab 是 FlatBuffers Table 访问器，保存了该表在二进制 buffer 中的位置引用
# 所有字段访问都通过 self._tab 进行 vtable 查找
    __slots__ = ['_tab']

# ============================================================
# FlatBuffer 根节点解析入口
# 从内存中的 FlatBuffer 二进制数据中解析出 QuantizationParameters 表
# 调用方式: obj = QuantizationParameters.GetRootAsQuantizationParameters(buf, offset)
#   - buf: bytes 类型，整个 FlatBuffer 二进制数据
#   - offset: 起始偏移量（通常为 0）
# TfliteConvertor.loadTFmodel() 通过 QuantizationParameters.GetRootAsQuantizationParameters(buf, 0) 调用
# ============================================================
    @classmethod
# 读取 uoffset（无符号偏移）值，这是 FlatBuffer 根表的起始位置
    def GetRootAsQuantizationParameters(cls, buf, offset):
# 从 buffer 中编码的 uoffset 偏移处开始解析根对象
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
# 创建表对象实例并初始化
        x = QuantizationParameters()
# Init 将 x._tab 绑定到 buffer 中的实际数据位置
        x.Init(buf, n + offset)
# 返回解析后的对象
        return x

# ------------------------------------------------------------
# 检查 buffer 是否包含有效的 TFLite 文件标识符
# 'TFL3' 魔术字 (0x54 0x46 0x4C 0x33) 是 TFLite 文件的签名
# 用于验证文件是否为有效的 FlatBuffer TFLite 模型
# ------------------------------------------------------------
    @classmethod
    def QuantizationParametersBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
# flatbuffers.util.BufferHasIdentifier 内部实现二进制签名比对
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # QuantizationParameters
# ------------------------------------------------------------
# 初始化 QuantizationParameters 表对象
# self._tab 是 flatbuffers.table.Table 实例，封装了对 FlatBuffer 二进制数据的访问
# buf: 完整的 FlatBuffer 二进制数据（bytes）
# pos: 该表在 buf 中的起始位置偏移
# 所有后续的字段访问器方法都通过 self._tab 进行 vtable 查找
# ------------------------------------------------------------
    def Init(self, buf, pos):
# 将 Table 访问器绑定到 buf 的 pos 位置
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizationParameters
# 读取 Min 向量字段（float32（32位浮点数） 数组）
# 浮点最小值（float32 向量），用于对称量化范围计算
# vtable 偏移量: 4
    def Min(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 float32（32位浮点数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # QuantizationParameters
# 以 Numpy ndarray 形式返回 Min 向量的全部元素
# vtable 偏移量: 4
    def MinAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # QuantizationParameters
# 返回 Min 向量的长度（元素个数）
# vtable 偏移量: 4
    def MinLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # QuantizationParameters
# 读取 MinIsNone 向量字段（标量 数组）
# 浮点最小值（float32 向量），用于对称量化范围计算
# vtable 偏移量: 4
    def MinIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # QuantizationParameters
# 读取 Max 向量字段（float32（32位浮点数） 数组）
# 浮点最大值（float32 向量），用于对称量化范围计算
# vtable 偏移量: 6
    def Max(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 float32（32位浮点数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # QuantizationParameters
# 以 Numpy ndarray 形式返回 Max 向量的全部元素
# vtable 偏移量: 6
    def MaxAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # QuantizationParameters
# 返回 Max 向量的长度（元素个数）
# vtable 偏移量: 6
    def MaxLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # QuantizationParameters
# 读取 MaxIsNone 向量字段（标量 数组）
# 浮点最大值（float32 向量），用于对称量化范围计算
# vtable 偏移量: 6
    def MaxIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # QuantizationParameters
# 读取 Scale 向量字段（float32（32位浮点数） 数组）
# 量化缩放因子（float32 向量），quantized = round(float / scale) + zero_point
# vtable 偏移量: 8
    def Scale(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 float32（32位浮点数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # QuantizationParameters
# 以 Numpy ndarray 形式返回 Scale 向量的全部元素
# vtable 偏移量: 8
    def ScaleAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # QuantizationParameters
# 返回 Scale 向量的长度（元素个数）
# vtable 偏移量: 8
    def ScaleLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # QuantizationParameters
# 读取 ScaleIsNone 向量字段（标量 数组）
# 量化缩放因子（float32 向量），quantized = round(float / scale) + zero_point
# vtable 偏移量: 8
    def ScaleIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

    # QuantizationParameters
# 读取 ZeroPoint 向量字段（int64（有符号64位整数） 数组）
# 量化零点（int64 向量），quantized = round(float / scale) + zero_point
# vtable 偏移量: 10
    def ZeroPoint(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int64（有符号64位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # QuantizationParameters
# 以 Numpy ndarray 形式返回 ZeroPoint 向量的全部元素
# vtable 偏移量: 10
    def ZeroPointAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # QuantizationParameters
# 返回 ZeroPoint 向量的长度（元素个数）
# vtable 偏移量: 10
    def ZeroPointLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # QuantizationParameters
# 读取 ZeroPointIsNone 字段（标量）
# 量化零点（int64 向量），quantized = round(float / scale) + zero_point
# vtable 偏移量: 10，对应 schema 中第 3 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def ZeroPointIsNone(self):
# 通过 vtable 偏移 10 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        return o == 0
# 从 buffer 的 (o + self._tab.Pos) 处读取 标量 值

# 字段不存在/未设置时返回默认值
    # QuantizationParameters
# 读取 DetailsType 字段（uint8（无符号8位整数））
# 量化详情类型（QuantizationDetails 枚举）
# vtable 偏移量: 12，对应 schema 中第 4 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def DetailsType(self):
# 通过 vtable 偏移 12 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 uint8（无符号8位整数） 值
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # QuantizationParameters
# 读取 Details 字段（Union 联合体类型）
# 量化详情联合体（如自定义量化参数）
# vtable 偏移量: 14
# 需要配合对应的 Type 枚举字段确定联合体的具体类型
    def Details(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
# Union 类型: 创建一个空的 Table 对象，然后通过 Union() 方法填充内容
            from flatbuffers.table import Table
# 返回的 Table 对象需要根据 Type 枚举转换为具体类型
            obj = Table(bytearray(), 0)
# 字段不存在时返回 None
            self._tab.Union(obj, o)
            return obj
        return None

    # QuantizationParameters
# 读取 QuantizedDimension 向量字段（int32（有符号32位整数） 数组）
# 量化作用的维度索引（per-channel 量化时使用）
# vtable 偏移量: 16
    def QuantizedDimension(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def QuantizationParametersStart(builder): builder.StartObject(7)
def QuantizationParametersAddMin(builder, min): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(min), 0)
def QuantizationParametersStartMinVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def QuantizationParametersAddMax(builder, max): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(max), 0)
def QuantizationParametersStartMaxVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def QuantizationParametersAddScale(builder, scale): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(scale), 0)
def QuantizationParametersStartScaleVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def QuantizationParametersAddZeroPoint(builder, zeroPoint): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(zeroPoint), 0)
def QuantizationParametersStartZeroPointVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def QuantizationParametersAddDetailsType(builder, detailsType): builder.PrependUint8Slot(4, detailsType, 0)
def QuantizationParametersAddDetails(builder, details): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(details), 0)
def QuantizationParametersAddQuantizedDimension(builder, quantizedDimension): builder.PrependInt32Slot(6, quantizedDimension, 0)
def QuantizationParametersEnd(builder): return builder.EndObject()