# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

# 此文件由 FlatBuffers 编译器 (flatc) 根据 TFLite schema 自动生成，请勿手动修改。
# 
# FlatBuffers 设计原理
# ═══════════════════
# TFLite 使用 Google FlatBuffers 作为模型序列化格式。相比 Protocol Buffers：
#   1. 零拷贝反序列化 — 无需解析即可直接读取二进制数据，CPU/内存开销极低
#   2. 按需字段访问 — vtable（虚表）机制，只读取需要的字段，不浪费
#   3. 紧凑二进制格式 — 文件体积小，适合 MCU 等资源受限设备
# 
# 文件结构
# ════════
# 本文件定义了 TFLite schema 中对应表的 Python 绑定类，包含：
#   - 读取部分：GetRootAsXxx / Init / 各字段访问器方法
#   - 写入部分：StartXxx / AddXxx / EndXxx 构建器函数（用于创建新的 FlatBuffer）
# 
# 字段访问模式
# ══════════════
# 每个访问器方法的实现遵循固定模式：
#   o = Offset(vtable_slot)  ← 通过 vtable 查找字段在 buffer 中的偏移
#   if o != 0:               ← o==0 表示字段未设置（该字段在模型中不存在）
#     return ReadData(o)     ← 从 buffer 的偏移位置读取数据
#   return default_value     ← 字段不存在时返回默认值
# 
# 此包被 TfliteConvertor.py 在编译管线中调用，将 .tflite 模型文件解析为 TinyEngine IR。

# ============================================================
# ResizeBilinearOptions — ResizeBilinearOptions — TFLite 算子参数表。存储在 Operator.BuiltinOptions 字段中，通过 BuiltinOptionsType 枚举类型确定具体解析方式。TfliteConvertor 在解析算子时将其转换为 TinyEngine IR 参数。
# ============================================================

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ResizeBilinearOptions(object):
# _tab 是 FlatBuffers Table 访问器，保存了该表在二进制 buffer 中的位置引用
# 所有字段访问都通过 self._tab 进行 vtable 查找
    __slots__ = ['_tab']

# ============================================================
# FlatBuffer 根节点解析入口
# 从内存中的 FlatBuffer 二进制数据中解析出 ResizeBilinearOptions 表
# 调用方式: obj = ResizeBilinearOptions.GetRootAsResizeBilinearOptions(buf, offset)
#   - buf: bytes 类型，整个 FlatBuffer 二进制数据
#   - offset: 起始偏移量（通常为 0）
# TfliteConvertor.loadTFmodel() 通过 ResizeBilinearOptions.GetRootAsResizeBilinearOptions(buf, 0) 调用
# ============================================================
    @classmethod
# 读取 uoffset（无符号偏移）值，这是 FlatBuffer 根表的起始位置
    def GetRootAsResizeBilinearOptions(cls, buf, offset):
# 从 buffer 中编码的 uoffset 偏移处开始解析根对象
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
# 创建表对象实例并初始化
        x = ResizeBilinearOptions()
# Init 将 x._tab 绑定到 buffer 中的实际数据位置
        x.Init(buf, n + offset)
# 返回解析后的对象
        return x

# ------------------------------------------------------------
# 检查 buffer 是否包含有效的 TFLite 文件标识符
# 'TFL3' 魔术字 (0x54 0x46 0x4C 0x33) 是 TFLite 文件的签名
# 用于验证文件是否为有效的 FlatBuffer TFLite 模型
# ------------------------------------------------------------
    @classmethod
    def ResizeBilinearOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
# flatbuffers.util.BufferHasIdentifier 内部实现二进制签名比对
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # ResizeBilinearOptions
# ------------------------------------------------------------
# 初始化 ResizeBilinearOptions 表对象
# self._tab 是 flatbuffers.table.Table 实例，封装了对 FlatBuffer 二进制数据的访问
# buf: 完整的 FlatBuffer 二进制数据（bytes）
# pos: 该表在 buf 中的起始位置偏移
# 所有后续的字段访问器方法都通过 self._tab 进行 vtable 查找
# ------------------------------------------------------------
    def Init(self, buf, pos):
# 将 Table 访问器绑定到 buf 的 pos 位置
        self._tab = flatbuffers.table.Table(buf, pos)

    # ResizeBilinearOptions
# 读取 AlignCorners 字段（bool（布尔值））
# vtable 偏移量: 8，对应 schema 中第 2 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def AlignCorners(self):
# 通过 vtable 偏移 8 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 bool（布尔值） 值
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
# 字段不存在/未设置时返回默认值
        return False

    # ResizeBilinearOptions
# 读取 HalfPixelCenters 字段（bool（布尔值））
# vtable 偏移量: 10，对应 schema 中第 3 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def HalfPixelCenters(self):
# 通过 vtable 偏移 10 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 bool（布尔值） 值
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
# 字段不存在/未设置时返回默认值
        return False

def ResizeBilinearOptionsStart(builder): builder.StartObject(4)
def ResizeBilinearOptionsAddAlignCorners(builder, alignCorners): builder.PrependBoolSlot(2, alignCorners, 0)
def ResizeBilinearOptionsAddHalfPixelCenters(builder, halfPixelCenters): builder.PrependBoolSlot(3, halfPixelCenters, 0)
def ResizeBilinearOptionsEnd(builder): return builder.EndObject()