# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

# 此文件由 FlatBuffers 编译器 (flatc) 根据 TFLite schema 自动生成，请勿手动修改。
# 
# FlatBuffers 设计原理
# ═══════════════════
# TFLite 使用 Google FlatBuffers 作为模型序列化格式。相比 Protocol Buffers：
#   1. 零拷贝反序列化 — 无需解析即可直接读取二进制数据，CPU/内存开销极低
#   2. 按需字段访问 — vtable（虚表）机制，只读取需要的字段，不浪费
#   3. 紧凑二进制格式 — 文件体积小，适合 MCU 等资源受限设备
# 
# 文件结构
# ════════
# 本文件定义了 TFLite schema 中对应表的 Python 绑定类，包含：
#   - 读取部分：GetRootAsXxx / Init / 各字段访问器方法
#   - 写入部分：StartXxx / AddXxx / EndXxx 构建器函数（用于创建新的 FlatBuffer）
# 
# 字段访问模式
# ══════════════
# 每个访问器方法的实现遵循固定模式：
#   o = Offset(vtable_slot)  ← 通过 vtable 查找字段在 buffer 中的偏移
#   if o != 0:               ← o==0 表示字段未设置（该字段在模型中不存在）
#     return ReadData(o)     ← 从 buffer 的偏移位置读取数据
#   return default_value     ← 字段不存在时返回默认值
# 
# 此包被 TfliteConvertor.py 在编译管线中调用，将 .tflite 模型文件解析为 TinyEngine IR。

# TensorType 枚举类
# 张量数据类型。TfliteConvertor 解析 Tensor.Type 后决定生成的 C 代码类型

class TensorType(object):
    FLOAT32 = 0  # FLOAT32=0 — 32 位浮点（0）
    FLOAT16 = 1  # FLOAT16=1 — 16 位浮点（1）
    INT32 = 2  # INT32=2 — 32 位整数（2）
    UINT8 = 3  # UINT8=3 — 8 位无符号整数（3）
    INT64 = 4  # INT64=4
    STRING = 5  # STRING=5
    BOOL = 6  # BOOL=6 — 布尔（6）
    INT16 = 7  # INT16=7 — 16 位整数（7）
    COMPLEX64 = 8  # COMPLEX64=8
    INT8 = 9  # INT8=9 — 8 位有符号整数（9）- TinyEngine 的核心数据类型
    FLOAT64 = 10  # FLOAT64=10
    COMPLEX128 = 11  # COMPLEX128=11