# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

# 此文件由 FlatBuffers 编译器 (flatc) 根据 TFLite schema 自动生成，请勿手动修改。
# 
# FlatBuffers 设计原理
# ═══════════════════
# TFLite 使用 Google FlatBuffers 作为模型序列化格式。相比 Protocol Buffers：
#   1. 零拷贝反序列化 — 无需解析即可直接读取二进制数据，CPU/内存开销极低
#   2. 按需字段访问 — vtable（虚表）机制，只读取需要的字段，不浪费
#   3. 紧凑二进制格式 — 文件体积小，适合 MCU 等资源受限设备
# 
# 文件结构
# ════════
# 本文件定义了 TFLite schema 中对应表的 Python 绑定类，包含：
#   - 读取部分：GetRootAsXxx / Init / 各字段访问器方法
#   - 写入部分：StartXxx / AddXxx / EndXxx 构建器函数（用于创建新的 FlatBuffer）
# 
# 字段访问模式
# ══════════════
# 每个访问器方法的实现遵循固定模式：
#   o = Offset(vtable_slot)  ← 通过 vtable 查找字段在 buffer 中的偏移
#   if o != 0:               ← o==0 表示字段未设置（该字段在模型中不存在）
#     return ReadData(o)     ← 从 buffer 的偏移位置读取数据
#   return default_value     ← 字段不存在时返回默认值
# 
# 此包被 TfliteConvertor.py 在编译管线中调用，将 .tflite 模型文件解析为 TinyEngine IR。

# ============================================================
# Tensor — 张量元信息（形状+数据类型+权重索引+量化参数）
# ============================================================

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Tensor(object):
# _tab 是 FlatBuffers Table 访问器，保存了该表在二进制 buffer 中的位置引用
# 所有字段访问都通过 self._tab 进行 vtable 查找
    __slots__ = ['_tab']

# ============================================================
# FlatBuffer 根节点解析入口
# 从内存中的 FlatBuffer 二进制数据中解析出 Tensor 表
# 调用方式: obj = Tensor.GetRootAsTensor(buf, offset)
#   - buf: bytes 类型，整个 FlatBuffer 二进制数据
#   - offset: 起始偏移量（通常为 0）
# TfliteConvertor.loadTFmodel() 通过 Tensor.GetRootAsTensor(buf, 0) 调用
# ============================================================
    @classmethod
# 读取 uoffset（无符号偏移）值，这是 FlatBuffer 根表的起始位置
    def GetRootAsTensor(cls, buf, offset):
# 从 buffer 中编码的 uoffset 偏移处开始解析根对象
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
# 创建表对象实例并初始化
        x = Tensor()
# Init 将 x._tab 绑定到 buffer 中的实际数据位置
        x.Init(buf, n + offset)
# 返回解析后的对象
        return x

# ------------------------------------------------------------
# 检查 buffer 是否包含有效的 TFLite 文件标识符
# 'TFL3' 魔术字 (0x54 0x46 0x4C 0x33) 是 TFLite 文件的签名
# 用于验证文件是否为有效的 FlatBuffer TFLite 模型
# ------------------------------------------------------------
    @classmethod
    def TensorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
# flatbuffers.util.BufferHasIdentifier 内部实现二进制签名比对
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # Tensor
# ------------------------------------------------------------
# 初始化 Tensor 表对象
# self._tab 是 flatbuffers.table.Table 实例，封装了对 FlatBuffer 二进制数据的访问
# buf: 完整的 FlatBuffer 二进制数据（bytes）
# pos: 该表在 buf 中的起始位置偏移
# 所有后续的字段访问器方法都通过 self._tab 进行 vtable 查找
# ------------------------------------------------------------
    def Init(self, buf, pos):
# 将 Table 访问器绑定到 buf 的 pos 位置
        self._tab = flatbuffers.table.Table(buf, pos)

    # Tensor
# 读取 Shape 向量字段（int32（有符号32位整数） 数组）
# 张量形状（int32 数组），如 [1, 32, 32, 16] 表示 NHWC 布局
# vtable 偏移量: 4
    def Shape(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tensor
# 以 Numpy ndarray 形式返回 Shape 向量的全部元素
# vtable 偏移量: 4
    def ShapeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Tensor
# 返回 Shape 向量的长度（元素个数）
# vtable 偏移量: 4
    def ShapeLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tensor
# 读取 ShapeIsNone 字段（标量）
# 张量形状（int32 数组），如 [1, 32, 32, 16] 表示 NHWC 布局
# vtable 偏移量: 4，对应 schema 中第 0 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def ShapeIsNone(self):
# 通过 vtable 偏移 4 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        return o == 0
# 从 buffer 的 (o + self._tab.Pos) 处读取 标量 值

# 字段不存在/未设置时返回默认值
    # Tensor
# 读取 Type 字段（int8（有符号8位整数））
# 数据类型，TensorType 枚举（INT8=9, UINT8=3, FLOAT32=0 等）
# vtable 偏移量: 6，对应 schema 中第 1 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def Type(self):
# 通过 vtable 偏移 6 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 int8（有符号8位整数） 值
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # Tensor
# 读取 Buffer 字段（uint32（无符号32位整数））
# 权重缓冲区在 Model.Buffers 中的索引。0 表示无权重（激活值张量）
# vtable 偏移量: 8，对应 schema 中第 2 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def Buffer(self):
# 通过 vtable 偏移 8 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 uint32（无符号32位整数） 值
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
# 字段不存在/未设置时返回默认值
        return 0

    # Tensor
# 读取 Name 字段（字符串类型）
# 张量名称（字符串，可用于调试）
# vtable 偏移量: 10
    def Name(self):
# String(offset) 返回 buffer 中该偏移处的 UTF-8 字符串
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
# return self._tab.String(...) = 读取字符串
            return self._tab.String(o + self._tab.Pos)
# 字段不存在时返回 None
        return None

    # Tensor
# 读取 Quantization 字段（子表引用类型 — 返回嵌套的 FlatBuffer 表对象）
# 量化参数（scale/zero_point 等），INT8 量化模型的关键信息
# vtable 偏移量: 12
    def Quantization(self):
# Indirect(offset) = 通过间接指针访问子表
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
# 创建子表对象并初始化为指向 buffer 中的对应位置
            x = self._tab.Indirect(o + self._tab.Pos)
# 调用子表对象的 Init 方法绑定数据
            from .QuantizationParameters import QuantizationParameters
# 返回子表对象
            obj = QuantizationParameters()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Tensor
# 读取 IsVariable 字段（bool（布尔值））
# 是否为变量（训练模式下可更新的张量）
# vtable 偏移量: 14，对应 schema 中第 5 个字段（0-indexed）
# FlatBuffer 模式: 通过 vtable 查找字段偏移 -> 若存在则读取值 -> 否则返回默认值
    def IsVariable(self):
# 通过 vtable 偏移 14 查找字段位置。Offset() 返回字段在 buffer 中的字节偏移（vtable 条目值）
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
# o != 0 表示字段在 vtable 中存在（即模型设置了该字段）
        if o != 0:
# 从 buffer 的 (o + self._tab.Pos) 处读取 bool（布尔值） 值
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
# 字段不存在/未设置时返回默认值
        return False

    # Tensor
# 读取 Sparsity 字段（子表引用类型 — 返回嵌套的 FlatBuffer 表对象）
# 稀疏参数（权重剪枝/结构化稀疏时使用）
# vtable 偏移量: 16
    def Sparsity(self):
# Indirect(offset) = 通过间接指针访问子表
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
# 创建子表对象并初始化为指向 buffer 中的对应位置
            x = self._tab.Indirect(o + self._tab.Pos)
# 调用子表对象的 Init 方法绑定数据
            from .SparsityParameters import SparsityParameters
# 返回子表对象
            obj = SparsityParameters()
# 字段不存在时返回 None
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Tensor
# 读取 ShapeSignature 向量字段（int32（有符号32位整数） 数组）
# 形状签名（用于动态形状模型）
# vtable 偏移量: 18
    def ShapeSignature(self, j):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        if o != 0:
# 读取该位置的 int32（有符号32位整数） 值
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tensor
# 以 Numpy ndarray 形式返回 ShapeSignature 向量的全部元素
# vtable 偏移量: 18
    def ShapeSignatureAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Tensor
# 返回 ShapeSignature 向量的长度（元素个数）
# vtable 偏移量: 18
    def ShapeSignatureLength(self):
# VectorLen(o) 读取向量头部的长度字段
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tensor
# 读取 ShapeSignatureIsNone 向量字段（标量 数组）
# 形状签名（用于动态形状模型）
# vtable 偏移量: 18
    def ShapeSignatureIsNone(self):
# Vector(o) 获取向量数据的起始偏移
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
# 通过索引 j * 元素字节大小 定位到第 j 个元素的位置
        return o == 0
# 读取该位置的 标量 值

def TensorStart(builder): builder.StartObject(8)
def TensorAddShape(builder, shape): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shape), 0)
def TensorStartShapeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TensorAddType(builder, type): builder.PrependInt8Slot(1, type, 0)
def TensorAddBuffer(builder, buffer): builder.PrependUint32Slot(2, buffer, 0)
def TensorAddName(builder, name): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def TensorAddQuantization(builder, quantization): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(quantization), 0)
def TensorAddIsVariable(builder, isVariable): builder.PrependBoolSlot(5, isVariable, 0)
def TensorAddSparsity(builder, sparsity): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(sparsity), 0)
def TensorAddShapeSignature(builder, shapeSignature): builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(shapeSignature), 0)
def TensorStartShapeSignatureVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TensorEnd(builder): return builder.EndObject()